export crum_transform, naive_darboux_chain

function _record_step!(history::Vector{CrumStepRecord{T}}, fold::Int, kappas, q::AbstractVector{T}) where {T}
    push!(history, CrumStepRecord{T}(fold, T.(collect(kappas)), minimum(q), maximum(q)))
    return history
end

"""
    crum_transform(xgrid, kappa, beta; shifts=nothing, q0=nothing, clip_reflectionless=true,
                   return_history=false, precision=nothing, digits=nothing)

Compute the KdV reflectionless potential generated by the target discrete
spectrum using the stable O(N^2) Prins-Wahls Crum-transform algorithm.

Assumptions:

- `kappa` is strictly increasing and positive.
- `beta` contains real nonzero target norming constants.
- This first implementation supports the explicit `q0(x)=0` seed
  trajectories.

Eigenvalues are processed from largest to smallest. If the number of remaining
eigenvalues is odd, the largest is added by a 1-fold step; otherwise the two
largest remaining eigenvalues are added by a 2-fold step.

Use `digits=<decimal digits>` or `precision=<BigFloat bits>` to run the whole
calculation in arbitrary precision. For example, `digits=80` is often useful
for large or tightly spaced soliton spectra.

Use `shifts=[s1, s2, ...]` to give each eigenvalue its own initial phase. The
solver internally uses `beta_n * exp(2*kappa_n*s_n)`.
"""
function crum_transform(
    xgrid,
    kappa,
    beta;
    shifts=nothing,
    q0=nothing,
    clip_reflectionless::Bool=true,
    return_history::Bool=false,
    precision=nothing,
    digits=nothing,
)
    bits = _precision_bits(precision, digits)
    bits === nothing && return _crum_transform_impl(
        xgrid,
        kappa,
        beta;
        shifts=shifts,
        q0=q0,
        clip_reflectionless=clip_reflectionless,
        return_history=return_history,
        number_type=nothing,
    )

    return setprecision(BigFloat, bits) do
        _crum_transform_impl(
            xgrid,
            kappa,
            beta;
            shifts=shifts,
            q0=q0,
            clip_reflectionless=clip_reflectionless,
            return_history=return_history,
            number_type=BigFloat,
        )
    end
end

function _crum_transform_impl(
    xgrid,
    kappa,
    beta;
    shifts=nothing,
    q0=nothing,
    clip_reflectionless::Bool=true,
    return_history::Bool=false,
    number_type=nothing,
)
    problem = CrumProblem(xgrid, kappa, beta; shifts=shifts, q0=q0, number_type=number_type)
    has_zero_background(problem.q0) ||
        throw(ArgumentError("only the q0(x)=0 seed trajectories are implemented"))
    T = eltype(problem.x)
    q = copy(problem.q0)
    N = length(problem.kappa)
    seeds = initial_seed_trajectories(problem)
    history = CrumStepRecord{T}[]
    do_clip = clip_reflectionless && has_zero_background(problem.q0)

    remaining = N
    while remaining > 0
        if isodd(remaining)
            idx = remaining
            kadd = problem.kappa[idx]

            @inbounds for i in eachindex(problem.x)
                q[i] = crum1_step(q[i], problem.x[i], kadd, component(seeds[idx], i))
            end
            do_clip && clip_reflectionless!(q)

            remaining -= 1
            @inbounds for n in 1:remaining
                target = seeds[n]
                ktarget = problem.kappa[n]
                for i in eachindex(problem.x)
                    new1, new2 = apply_crum1_dressing(
                        problem.x[i],
                        kadd,
                        component(seeds[idx], i),
                        ktarget,
                        component(target, i),
                    )
                    setcomponent!(target, i, new1, new2)
                end
            end

            _record_step!(history, 1, [kadd], q)
        else
            idx1 = remaining
            idx2 = remaining - 1
            k1 = problem.kappa[idx1]
            k2 = problem.kappa[idx2]

            @inbounds for i in eachindex(problem.x)
                q[i] = crum2_step(
                    q[i],
                    problem.x[i],
                    k1,
                    component(seeds[idx1], i),
                    k2,
                    component(seeds[idx2], i),
                )
            end
            do_clip && clip_reflectionless!(q)

            remaining -= 2
            @inbounds for n in 1:remaining
                target = seeds[n]
                ktarget = problem.kappa[n]
                for i in eachindex(problem.x)
                    new1, new2 = apply_crum2_dressing(
                        problem.x[i],
                        k1,
                        component(seeds[idx1], i),
                        k2,
                        component(seeds[idx2], i),
                        ktarget,
                        component(target, i),
                    )
                    setcomponent!(target, i, new1, new2)
                end
            end

            _record_step!(history, 2, [k1, k2], q)
        end
    end

    result = CrumTransformResult{T}(
        copy(problem.x),
        copy(problem.kappa),
        copy(problem.beta),
        effective_beta(problem),
        copy(problem.shifts),
        copy(problem.q0),
        q,
        history,
    )
    return return_history ? result : result.q
end

"""
    naive_darboux_chain(xgrid, kappa, beta; order=:smallest_first, shifts=nothing, q0=nothing,
                        precision=nothing, digits=nothing)

Reference implementation that adds all eigenvalues with repeated 1-fold
Darboux steps. This is useful for demonstrations of artificial singularities
and floating-point instability.
"""
function naive_darboux_chain(
    xgrid,
    kappa,
    beta;
    order::Symbol=:smallest_first,
    shifts=nothing,
    q0=nothing,
    clip_reflectionless::Bool=false,
    return_history::Bool=false,
    precision=nothing,
    digits=nothing,
)
    bits = _precision_bits(precision, digits)
    bits === nothing && return _naive_darboux_chain_impl(
        xgrid,
        kappa,
        beta;
        order=order,
        shifts=shifts,
        q0=q0,
        clip_reflectionless=clip_reflectionless,
        return_history=return_history,
        number_type=nothing,
    )

    return setprecision(BigFloat, bits) do
        _naive_darboux_chain_impl(
            xgrid,
            kappa,
            beta;
            order=order,
            shifts=shifts,
            q0=q0,
            clip_reflectionless=clip_reflectionless,
            return_history=return_history,
            number_type=BigFloat,
        )
    end
end

function _naive_darboux_chain_impl(
    xgrid,
    kappa,
    beta;
    order::Symbol=:smallest_first,
    shifts=nothing,
    q0=nothing,
    clip_reflectionless::Bool=false,
    return_history::Bool=false,
    number_type=nothing,
)
    order in (:smallest_first, :largest_first) ||
        throw(ArgumentError("order must be :smallest_first or :largest_first"))

    problem = CrumProblem(xgrid, kappa, beta; shifts=shifts, q0=q0, number_type=number_type)
    has_zero_background(problem.q0) ||
        throw(ArgumentError("only the q0(x)=0 seed trajectories are implemented"))
    T = eltype(problem.x)
    q = copy(problem.q0)
    seeds = initial_seed_trajectories(problem)
    pending = collect(1:length(problem.kappa))
    history = CrumStepRecord{T}[]
    do_clip = clip_reflectionless && has_zero_background(problem.q0)

    while !isempty(pending)
        pos = order === :smallest_first ? firstindex(pending) : lastindex(pending)
        idx = pending[pos]
        deleteat!(pending, pos)
        kadd = problem.kappa[idx]

        @inbounds for i in eachindex(problem.x)
            q[i] = crum1_step(q[i], problem.x[i], kadd, component(seeds[idx], i))
        end
        do_clip && clip_reflectionless!(q)

        @inbounds for n in pending
            target = seeds[n]
            ktarget = problem.kappa[n]
            for i in eachindex(problem.x)
                new1, new2 = apply_crum1_dressing(
                    problem.x[i],
                    kadd,
                    component(seeds[idx], i),
                    ktarget,
                    component(target, i),
                )
                setcomponent!(target, i, new1, new2)
            end
        end

        _record_step!(history, 1, [kadd], q)
    end

    result = CrumTransformResult{T}(
        copy(problem.x),
        copy(problem.kappa),
        copy(problem.beta),
        effective_beta(problem),
        copy(problem.shifts),
        copy(problem.q0),
        q,
        history,
    )
    return return_history ? result : result.q
end
